from LAB import LAB
from MultplePathsNeedlemanAligner import MultplePathsNeedlemanAligner
from SimpleNeedlemanAligner import SimpleNeedleManAligner

if __name__ == '__main__':
    pairs = [ 
        ['GAATTCAGTTAA','AGTTA']
        # ['AGATA', 'AAGTA'],
        # ['GAATTCAGTTA', 'GGATCGA'],
        # ['GAATTCAGS', 'GGATCGAERDWER'],
        # ['GAATTCAGSUYWEDGFUYWDE', 'GGATCGAERDWER'],
        # ['GAAT', 'DWER'],
        # ['CTTTCTGTCCCGCCCTTCCTCTGACTGTGTCTTGATTTCCTATTCTGAGAGGCTATTGCTCAGCGGTTTCCGTGGCAACAGTAAAGCGTGGGAATTACAGATAAATTAAAACTGTGGAACCCCTTTCCTCGGCTGCCGCCAAGGTGTTCGGTCCTTCCGAGGAAGCTAAGGCCGCGTTGGGGTGAGACCCTCACTTCATCCGGTGAGTAGCACCGCGTCCGGCAGCCCCAGCCCCACACTCGCCCGCGCTATGGCCTCCGTCTCCCAGCTTGCCTGCATCTACTCTGCCCTCATTCTGCAGGACTATGAGGTGACCTTTACGGAGGATAAGATCAATGCCCTTATTAAAGCAGCCAGTGTAAATATTGAAACTTTTTGGCCTGGCTTGTTTGCAAAGGTCCTGGCCAACGTCAACATTGGGAGCCACATCTGCAGTGTAGAGGGGGGGAAAAAAACGTGACTGCGCGTCGTGAGCTCGCTGAGACGTTCTGGACGGGGGACAGGCCGTGGGGTTTCTCAGATAACTGGGCCCCTGGGCTCAGGAGGCCTGCACCCTCTGC',
        #  'CTTTCTGTCCCGCCCTTCCTCTGACTGTGTCTTGATTTCCTATTCTGAGAGGCTATTGCTCAGCGGTTTCCGTGGCAACAGTAAAGCGTGGGAATTACAGATAAATTAAAACTGTGGAACCCCTTTCCTCGGCTGCCGCCAAGGTGTTCGGTCCTTCCGAGGAAGCTAAGGCCGCGTTGGGGTGAGACCCTCACTTCATCCGGTGAGTAGCACCGCGTCCGCCCACACTCGCCCGCGCTATGGCCTCCGTCTCCCAGCTTGCCTGCATCTACTCTGCCCTCATTCTGCAGGACTATGAGGTGACCTTTACGGAGGATAAGATCAATGCCCTTATTAAAGCAGCCAGTGTAAATATTGAAACTTTTTGGCCTGGCTTGTTTGCAAAGGTCCTGGCCAACGTCAACATTGGGAGCCACATCTGCAGTGTAGAGGGGAAAACGTGACTGCGCGTCGTGAGCTCGCTGAGACGTTCTGGACGGGGGACAGGCCGTGGGGTTTCTCAGATAACTGGGCCCCTGGGCTCAGGAGGTTTTTTTTCTGC']
    ]
    lab = LAB()
    for pair in pairs:
        lab.setAligner(SimpleNeedleManAligner(pair))
        aligner = lab.getAligner()
        aligner.filloutMatrix()
        traceback = aligner.getTraceback()
        print(aligner.graphTraceback(traceback))
        print(aligner.humaReadableRepresentation(traceback))
